site_name: Godot Kotlin/Jvm
docs_dir: src/doc

repo_name: 'utopia-rise/godot-kotlin-jvm'
repo_url: 'https://github.com/utopia-rise/godot-kotlin-jvm'

theme:
  name: material
  favicon: assets/img/favicon.ico
  palette:
    primary: indigo
    accent: light-blue
  logo: assets/img/logo.png

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/utopia-rise

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css


nav:
  - Overview: index.md
  - Getting started:
      - Project Setup: getting-started/project-setup.md
      - IDE: getting-started/ide.md
      - Gradle: getting-started/gradle.md
      - Add first class: getting-started/add-first-class.md
  - User guide:
    - Classes: user-guide/classes.md
    - Properties: user-guide/properties.md
    - Signals: user-guide/signals.md
    - Functions: user-guide/functions.md
    - Exporting: user-guide/exporting.md
    - API differences: user-guide/api-differences.md
  - Advanced:
    - Custom Src dirs: advanced/custom-src-dirs.md
    - Custom gradle wrapper path: advanced/custom_gradle_wrapper_path.md
    - Commandline args: advanced/commandline-args.md
    - Kotlin singletons: advanced/kotlin-singleton.md
  - Contribution:
    - General: contribution/general.md
    - Guidelines: contribution/guidelines.md
    - Setup: contribution/setup.md
    - Build with C# support: contribution/build-with-csharp-support.md
    - Knowledge base:
        - Artefact differentiation: contribution/knowledge-base/artefact-differentiation.md
        - Entry generation: contribution/knowledge-base/entry-generation.md
  - Versioning: versioning.md
  - Supported platforms: supported-platforms.md
