name: Check PR - JVM Godot Gradle Plugin
on:
  pull_request:
    paths:
      - 'kt/buildSrc/**'
      - 'kt/gradle/**'
      - 'kt/entry-generation/**'
      - 'kt/utils/godot-build-props/**'
      - 'kt/plugins/godot-gradle-plugin/**'
      - '.github/workflows/check-pr-jvm-gradle-plugin.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: kt/
          build-root-directory: kt/
          arguments: godot-gradle-plugin:build
