name: Check PR - Engine
on:
  pull_request:
    paths:
      - 'src/**'
      - 'config.py'
      - 'register_types.cpp'
      - 'register_types.h'
      - 'SCsub'
      - '.github/workflows/check-pr-engine.yaml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: x11
          - os: macos-latest
            platform: osx
          - os: windows-latest
            platform: windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone Godot Engine
        uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: 3.2.3-stable
      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
        with:
          path: module/kotlin_jvm
          submodules: recursive
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
      - name: Build editor debug
        run: |
          scons platform=${{ matrix.platform }}
