name: Create Draft Release
on:
  push:
    tags:
      - '\d+.\d+.\d+-\d+.\d+.\d+-SNAPSHOT'
      - '\d+.\d+.\d+-\d+.\d+.\d+'

jobs:
  create-draft-release:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          body: |
            The pre built engines are the zip files.
            The other files are export templates needed for exporting your game. See [exporting](https://godot-kotl.in/en/latest/user-guide/exporting/) documentation on how to use them.

      - name: Output release url file
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt

      - name: Output supported godot version file
        run: echo $(echo "$GITHUB_REF" | grep -Po '^(?:refs\/tags\/\d+.\d+.\d+-)\K(\d+.\d+.\d+)((?=-SNAPSHOT$)|$)') > godot_version.txt

      - name: Output godot kotlin jvm version file
        run: echo $(echo "$GITHUB_REF" | grep -Po '^(?:refs\/tags\/)\K\d+.\d+.\d+-\d+.\d+.\d+(?:-SNAPSHOT)$') > godot_kotlin_jvm_version.txt

      - name: Save Release URL File for publish
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt

      - name: Save supported godot version for publish
        uses: actions/upload-artifact@v1
        with:
          name: godot_version
          path: godot_version.txt

      - name: Save godot kotlin jvm version for publish
        uses: actions/upload-artifact@v1
        with:
          name: godot_kotlin_jvm_version
          path: godot_kotlin_jvm_version.txt